---
abstract: 'A date and time object'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DateTime
  repository: http://hg.urth.org/hg/DateTime.pm
version: 0.62
